# (1) Numpy

O NumPy é uma biblioteca fundamental para a computação científica em Python, especialmente quando se trabalha com grandes conjuntos de dados numéricos. Ele oferece uma série de vantagens que o tornam uma ferramenta indispensável para diversos campos, como:

1. Eficiência em cálculos numéricos:

  - **Arrays:** O NumPy introduz o conceito de arrays, que são estruturas de dados homogêneas (todos os elementos têm o mesmo tipo de dado) e multidimensionais. Eles são muito mais eficientes em termos de memória e velocidade de processamento do que as listas padrão do Python.
  - **Vetorização:** O NumPy permite realizar operações matemáticas em arrays inteiros de uma só vez, eliminando a necessidade de loops explícitos. Isso resulta em um código mais conciso e eficiente.

2. Ampla variedade de funções:

  - **Matemáticas:** O NumPy oferece uma vasta gama de funções matemáticas, como trigonometria, álgebra linear, estatística e geração de números aleatórios.
  - **Manipulação de arrays:** Ele fornece ferramentas poderosas para criar, modificar e manipular arrays, como indexação, fatiamento, ordenação e redimensionamento.

3. Integração com outras bibliotecas de grande importância em Análise de Dados:

  - **SciPy:** O NumPy serve como base para a biblioteca SciPy, que oferece algoritmos mais avançados para otimização, processamento de sinais, estatística e muito mais.
  - **Pandas:** O Pandas, utilizado para análise de dados, é construído sobre o NumPy e oferece estruturas de dados mais flexíveis para trabalhar com dados tabulares.
  - **Scikit-learn:** Essa biblioteca de machine learning utiliza o NumPy para representar dados e realizar cálculos numéricos.

4. Comunidade e recursos:

  - **Grande comunidade:** O NumPy possui uma comunidade ativa de desenvolvedores e usuários, o que significa que você encontrará muitos recursos, tutoriais e exemplos online.
  - **Documentação completa:** A documentação oficial do NumPy é extensa e bem detalhada, cobrindo todos os aspectos da biblioteca.

5. Em resumo, o NumPy é fundamental para:

  - **Ciência de dados:** Análise de dados, machine learning, deep learning
  - **Engenharia:** Simulação, processamento de sinais, otimização
  - **Finanças:** Modelagem financeira, análise de séries temporais
  - **Visualização de dados:** Criação de gráficos e visualizações

5. Quando usar NumPy:

  - **Grandes conjuntos de dados numéricos:** O NumPy é ideal para trabalhar com matrizes e vetores de grandes dimensões.
  - **Operações matemáticas complexas:** Ele oferece um conjunto completo de funções para realizar cálculos numéricos de forma eficiente.
  - **Desempenho:** Se a velocidade de execução for crucial para sua aplicação, o NumPy é a escolha certa.

## (1.1) Primeiros passos - Definição de um `array`

In [ ]:
# Importe a biblioteca `numpy` apelidando ela de `np`
import numpy as np

**O que são Arrays?**
Imagine uma lista de números, como `[1, 2, 3, 4]`. Essa é a ideia básica de um array unidimensional. Um array é uma estrutura de dados que armazena uma coleção de elementos do mesmo tipo. Esses elementos podem ser números, strings, ou até mesmo outros arrays.

In [ ]:
# Criando uma lista
my_list = [1, 2, 3, 4, 5, 6]

# Convertendo a lista para um array NumPy
vector = np.array(my_list)

# Visualizando array unidimensional
vector

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Criando duas listas
list_one = my_list[:3] # Linha 1 (array unidimensional)
list_two = my_list[3:] # Linha 2 (array unidimensional)

# Convertendo as listas para arrays NumPy
matrix = np.array([list_one, list_two])

# Visualizando array multidimensional
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Veja, agora, o tipo de dado que está sendo trabalhado
print(type(vector))
print(type(matrix))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### (1.1.1) Formas práticas de criar um array

1. `np.zeros()`

In [ ]:
# Array unidimensional
np.zeros(shape=10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Array unidimensional
np.zeros(shape=10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Array multidimensional
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Array multidimensional
np.zeros(shape=(3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# Array multidimensional
np.zeros(shape=(10, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
# Array multidimensional
np.zeros(shape=(10, 1), dtype=int)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

2. `np.ones()`

In [ ]:
# Array unidimensional
np.ones(shape=10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Array unidimensional
np.ones(shape=10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
# Array multidimensional
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Array multidimensional
np.ones(shape=(3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
# Array multidimensional
np.ones(shape=(10, 1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
# Array multidimensional
np.ones(shape=(10, 1), dtype=int)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

3. `np.full()`

In [ ]:
# Array multidimensional
np.full(shape=(2, 3), fill_value=1/2)

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

4. `np.eye()`

In [ ]:
# Array multidimensional
np.eye(N=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Array multidimensional
np.eye(N=3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
# Array multidimensional
np.eye(N=3, M=4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

5. `np.arange()` e `np.linspace()`

In [ ]:
# Array unidimensional
np.arange(start=0, stop=10, step=2)

array([0, 2, 4, 6, 8])

In [ ]:
# Array unidimensional
np.arange(start=-12, stop=0, step=2)

array([-12, -10,  -8,  -6,  -4,  -2])

In [ ]:
# Array unidimensional
np.linspace(start=0, stop=10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
# Array unidimensional
np.linspace(start=0, stop=10, num=5, dtype=int)

array([ 0,  2,  5,  7, 10])

In [ ]:
# Array unidimensional
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# Array unidimensional
np.linspace(1, 10, 10, dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Array unidimensional
np.linspace(start=-4, stop=4, num=1000)

array([-4.        , -3.99199199, -3.98398398, -3.97597598, -3.96796797,
       -3.95995996, -3.95195195, -3.94394394, -3.93593594, -3.92792793,
       -3.91991992, -3.91191191, -3.9039039 , -3.8958959 , -3.88788789,
       -3.87987988, -3.87187187, -3.86386386, -3.85585586, -3.84784785,
       -3.83983984, -3.83183183, -3.82382382, -3.81581582, -3.80780781,
       -3.7997998 , -3.79179179, -3.78378378, -3.77577578, -3.76776777,
       -3.75975976, -3.75175175, -3.74374374, -3.73573574, -3.72772773,
       -3.71971972, -3.71171171, -3.7037037 , -3.6956957 , -3.68768769,
       -3.67967968, -3.67167167, -3.66366366, -3.65565566, -3.64764765,
       -3.63963964, -3.63163163, -3.62362362, -3.61561562, -3.60760761,
       -3.5995996 , -3.59159159, -3.58358358, -3.57557558, -3.56756757,
       -3.55955956, -3.55155155, -3.54354354, -3.53553554, -3.52752753,
       -3.51951952, -3.51151151, -3.5035035 , -3.4954955 , -3.48748749,
       -3.47947948, -3.47147147, -3.46346346, -3.45545546, -3.44

### (1.1.2) Atributos de `array`

In [ ]:
# Acessando os atributos
print("Shape:", vector.shape)
print("Dtype:", vector.dtype)
print("Ndim:", vector.ndim)
print("Size:", vector.size)
print()
print(vector)

Shape: (6,)
Dtype: int64
Ndim: 1
Size: 6

[1 2 3 4 5 6]


In [ ]:
# Acessando os atributos
print("Shape:", matrix.shape)
print("Dtype:", matrix.dtype)
print("Ndim:", matrix.ndim)
print("Size:", matrix.size)
print()
print(matrix)

Shape: (2, 3)
Dtype: int64
Ndim: 2
Size: 6

[[1 2 3]
 [4 5 6]]


## (1.2) Indexação, Fatiamento e Manipulação de `array`

In [ ]:
# Definição de um array
arr1 = np.array([2, 1, 5, 3, 7, 4, 6, 8])

# Visualização
arr1

array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
# Definição de um array
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Visualização
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Definição de um array
arr3 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Visualização
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

-  Comandos para Indexação e Fatiamento:

In [ ]:
arr1[0] # Acessar elementos específicos: array[índice]

np.int64(2)

In [ ]:
arr1[0:2] # Fatiamento de arrays (arrays unidimensionais e multidimensionais): array[início:fim]

array([2, 1])

In [ ]:
arr2[:, 2] # Seleção de linhas e colunas em arrays 2D: array[select_row, select_column]

array([3, 6, 9])

In [ ]:
arr2[2, :] # Seleção de linhas e colunas em arrays 2D: array[select_row, select_column]

array([7, 8, 9])

-  Comandos para Indexação e Fatiamento Booleano:

In [ ]:
arr3 >= 5

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
# Condição
five_up = arr3 >= 5

# Fatiando conforme a condição
arr3[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr3 % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [ ]:
# Elementos pares
divisible_by_2 = arr3[arr3 % 2 == 0]

# Visualização
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
# Elementos maiores que 2 e menores que 11
(arr3 > 2) & (arr3 < 11)

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

In [ ]:
# Condição dupla
c = arr3[(arr3 > 2) & (arr3 < 11)]

# Visualização
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Condição tripla
c = arr3[(arr3 > 2) & (arr3 < 11) & (arr3 % 2 == 0)]

# Visualização
c

array([ 4,  6,  8, 10])

- Manipulação da *forma* de `array` e concatenação de `arrays`:

In [ ]:
# Definindo array
v1 = np.arange(6)

# Visualizar
v1

array([0, 1, 2, 3, 4, 5])

In [ ]:
# Alterar a forma de v1
v2 = v1.reshape(2, 3)

# Visualizar
v2

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# Alterar a forma de v1
v3 = v1.reshape(3, 2)

# Visualizar
v3

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
# Alterar a forma de v1
v4 = v1.reshape(v1.size, 1)

# Visualizar
v4

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
# Vetor Linha
row_vector = v1[np.newaxis, :]

# Visualizar
row_vector

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
# Vetor Coluna
col_vector = v1[:, np.newaxis]

# Visualizar
col_vector

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
print(f"Forma de v1: {v1.shape}")
print(f"Forma de v2: {v2.shape}")
print(f"Forma de v3: {v3.shape}")
print(f"Forma de v4: {v4.shape}")
print(f"Forma de row_vector: {row_vector.shape}")
print(f"Forma de col_vector: {col_vector.shape}")

Forma de v1: (6,)
Forma de v2: (2, 3)
Forma de v3: (3, 2)
Forma de v4: (6, 1)
Forma de row_vector: (1, 6)
Forma de col_vector: (6, 1)


In [ ]:
# Considere o array
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Visualizar
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Usando a função np.ravel()
array_ravel = np.ravel(matrix, order="C")

# Visualizando
array_ravel

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Usando a função np.ravel()
array_ravel = np.ravel(matrix, order="F")

# Visualizando
array_ravel

array([1, 4, 2, 5, 3, 6])

In [ ]:
# Usando o método array.flatten()
array_flatten = matrix.flatten(order="C")

# Visualizando
array_flatten

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Usando o método array.flatten()
array_flatten = matrix.flatten(order="F")

# Visualizando
array_flatten

array([1, 4, 2, 5, 3, 6])

- Alterando o tipo dos elementos do `array`

In [ ]:
# Modificando para um array de pontos flutuantes
array_flatten.astype(np.float64)

array([1., 4., 2., 5., 3., 6.])

In [ ]:
# Modificando para um array de pontos flutuantes
np.array(array_flatten, dtype=np.float64)

array([1., 4., 2., 5., 3., 6.])

In [ ]:
# Definindo um array de zeros
array_zeros = np.zeros(shape=(3, 3))

# Visualizar o array de zeros
print(array_zeros)

# Iterar pelas linhas do array
for i in range(1, array_zeros.shape[0] + 1):
  # Iterar pelas colunas do array
  for j in range(1, array_zeros.shape[1] + 1):
    # Preencher o array com o valor da divisão de i por j
    array_zeros[i - 1, j - 1] = i / j

# Visualizar o array preenchido
print("\n", array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[1.         0.5        0.33333333]
 [2.         1.         0.66666667]
 [3.         1.5        1.        ]]


In [ ]:
# Modificando para um array de inteiros
np.array(array_zeros, dtype=np.int64)

array([[1, 0, 0],
       [2, 1, 0],
       [3, 1, 1]])

In [ ]:
# Modificando para um array de inteiros
array_zeros.astype(np.int64)

array([[1, 0, 0],
       [2, 1, 0],
       [3, 1, 1]])

- Concateção de `arrays`:

In [ ]:
# Definindo arrays para exemplo de concatenação
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [ ]:
# Concatenando verticalmente (ao longo do eixo 0)
c1 = np.concatenate((a, b), axis=0)

# Visualizar
c1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# Concatenando horizontalmente (ao longo do eixo 1)
d1 = np.concatenate((a, b.T), axis=1)

# Visualizar
d1

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
print(b)   # array original
print()
print(b.T) # array transposto

[[5 6]]

[[5]
 [6]]


In [ ]:
# Concatenando verticalmente
c2 = np.vstack((a, b))

# Visualizar
c2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# Comparação
c1 == c2

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [ ]:
# Concatenando horizontalmente
d2 = np.hstack((a, b.T))

# Visualizar
d2

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
# Comparação
d1 == d2

array([[ True,  True,  True],
       [ True,  True,  True]])

## (1.3) Geração de arrays aleatórios

1. Comandos iniciais para geração de arrays aleatórios

In [ ]:
# Array multidimensional uniformimente distribuído
np.random.rand(3, 2)

array([[0.17432373, 0.68358055],
       [0.16588367, 0.84557576],
       [0.35662479, 0.79577087]])

In [ ]:
# Array multidimensional uniformimente distribuído
np.random.rand(10, 1)

array([[0.03977201],
       [0.28006468],
       [0.31847334],
       [0.83145634],
       [0.96719952],
       [0.87712602],
       [0.77709622],
       [0.46016881],
       [0.93752079],
       [0.43147844]])

In [ ]:
# Array multidimensional uniformimente distribuído
np.random.rand(10)

array([0.52101091, 0.59388395, 0.29306593, 0.42801099, 0.3866725 ,
       0.84307729, 0.35863176, 0.58580119, 0.36667066, 0.10562839])

In [ ]:
# Array multidimensional uniformimente distribuído
np.random.rand(3, 4)

array([[0.17479408, 0.61496061, 0.67102914, 0.20843669],
       [0.81797847, 0.83429252, 0.22756687, 0.69454396],
       [0.04020835, 0.37639739, 0.57696719, 0.83315445]])

In [ ]:
# Array multidimensional uniformimente distribuído
np.random.rand(3, 2)

array([[0.77628876, 0.70039879],
       [0.12323077, 0.30244659],
       [0.37857712, 0.38166046]])

In [ ]:
# Números aleatórios dentro de um intervalo
np.random.randint(low=0, high=10, size=10)

array([9, 2, 9, 4, 0, 2, 9, 3, 0, 6])

In [ ]:
# Números aleatórios dentro de um intervalo
np.random.randint(low=0, high=10, size=(10, 1))

array([[0],
       [3],
       [1],
       [4],
       [5],
       [3],
       [0],
       [8],
       [8],
       [9]])

In [ ]:
# Números (inteiros) aleatórios dentro de um intervalo
np.random.randint(low=0, high=10, size=(5, 2))

array([[6, 9],
       [3, 9],
       [6, 6],
       [8, 2],
       [2, 2]])

1. Simulando algumas distribuições de probabilidade

In [ ]:
# Amostra Aleatória: Uniforme(0, 1)
np.random.uniform(low=0, high=1, size=20)

array([0.96394421, 0.19568292, 0.48183485, 0.5135139 , 0.30495056,
       0.57657349, 0.6013924 , 0.16275238, 0.13507563, 0.46748413,
       0.79047395, 0.5560653 , 0.11657078, 0.74849781, 0.97417227,
       0.133183  , 0.68500059, 0.54559619, 0.50415522, 0.17795873])

In [ ]:
# Amostra Aleatória: Uniforme(0, 2)
np.random.uniform(low=0, high=2, size=20)

array([1.09012235, 0.42856418, 1.41812876, 0.27849022, 0.61012335,
       1.76120563, 1.74279477, 1.32760453, 0.0036202 , 0.62897737,
       1.36299   , 0.57588693, 0.21479772, 1.92084603, 1.06727384,
       1.42773656, 0.66910292, 0.37790931, 0.12452639, 0.60383478])

In [ ]:
# Amostra Aleatória: Uniforme(1, 2)
np.random.uniform(low=1, high=2, size=20)

array([1.7530136 , 1.12715586, 1.84672446, 1.29760856, 1.26503075,
       1.93397292, 1.66852468, 1.49279467, 1.24166334, 1.0257346 ,
       1.33792743, 1.91994996, 1.28688398, 1.37237242, 1.21114098,
       1.85532061, 1.25656724, 1.88656319, 1.37936852, 1.01787391])

In [ ]:
# Amostra Aleatória: Normal(0, 1)
np.random.normal(loc=0, scale=1, size=20)

array([-0.11071114, -0.66796887, -0.22931268, -0.91605761,  0.49286821,
        0.51497619,  0.73927367, -1.31854051, -1.89844593,  1.28153567,
        0.65936979,  1.93235317,  2.46320642,  0.24851089, -1.00370983,
       -1.3515705 , -0.18459245,  0.46876827, -0.21805533,  0.82014016])

In [ ]:
# Amostra Aleatória: Normal(5, 1)
np.random.normal(loc=5, scale=1, size=20)

array([4.5220023 , 4.86422836, 4.23922873, 4.3734223 , 6.12924756,
       4.85889069, 5.70791834, 5.4984772 , 4.01354369, 3.14329646,
       5.87791099, 3.11066766, 4.42588074, 5.41462647, 2.80448595,
       4.59935284, 6.65138069, 5.99862599, 5.48446342, 3.01637249])

In [ ]:
# Amostra Aleatória: Normal(-5, 1)
np.random.normal(loc=-5, scale=1, size=20)

array([-3.9338915 , -3.91555253, -5.41032412, -7.30826552, -5.10987412,
       -6.52855557, -5.62233532, -4.88276078, -4.32951087, -5.18008367,
       -5.65080988, -4.91306629, -5.64767321, -5.05412831, -5.60463807,
       -5.08786648, -4.05898588, -5.45026213, -2.19821697, -4.65468365])

In [ ]:
# Amostra Aleatória: Bernoulli(0.5)
np.random.binomial(n=1, p=0.5, size=20)

array([1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0])

In [ ]:
# Amostra Aleatória: Binomial(10, 0.5)
np.random.binomial(n=10, p=0.5, size=20)

array([4, 4, 5, 4, 3, 5, 6, 8, 2, 4, 3, 4, 2, 3, 6, 2, 6, 3, 9, 5])

In [ ]:
# Amostra Aleatória: X^2(5)
np.random.chisquare(df=5, size=20)

array([ 5.84402268,  2.19479588,  6.34026161,  4.40004671,  1.55721316,
        3.95762891,  0.73049316,  6.38819224,  3.10203902,  7.56943161,
        3.47018181,  4.45454761,  1.28898589,  1.07981764,  2.99784959,
        2.62674338,  5.0344179 ,  3.47135628, 12.3556456 ,  8.54656748])

In [ ]:
# Amostra Aleatória: X^2(10)
np.random.chisquare(df=10, size=20)

array([ 6.49555141,  5.62562978, 13.51712884,  9.58135825,  8.54460594,
       14.84163535,  5.49949419, 10.42226801, 12.52773747, 14.3982742 ,
       12.37643038,  9.90270047, 10.3986731 ,  2.56989392,  8.56007961,
       14.86436823,  5.49764667, 11.78172057,  9.50462016, 10.22318102])

In [ ]:
# Amostra Aleatória: F(1, 2)
np.random.f(dfnum=1, dfden=2, size=20)

array([2.51104886e-03, 2.91996063e-02, 1.42299503e+00, 5.90531298e-01,
       1.04533211e-01, 4.01508695e+00, 1.32305469e+01, 1.70635066e+00,
       9.79851837e-01, 7.44601030e-01, 2.25689380e-01, 9.03410650e-01,
       3.15584561e-02, 5.35606701e+00, 4.37518494e-03, 1.15004639e-01,
       1.00799506e+00, 4.11652808e+01, 1.80270927e-02, 1.39704241e-01])

In [ ]:
# Amostra Aleatória: F(2, 3)
np.random.f(dfnum=2, dfden=3, size=20)

array([4.68791417, 6.5914005 , 0.29662385, 0.32583159, 0.76479487,
       0.48016427, 0.0480275 , 0.3629278 , 1.03659626, 0.2709923 ,
       0.41494847, 1.07614852, 0.57230209, 0.25617814, 7.53773073,
       0.08836587, 0.29004512, 0.90297261, 0.48359801, 8.50863128])

In [ ]:
# Amostra Aleatória: Exponencial(1)
np.random.exponential(scale=1, size=20)

array([0.47985725, 0.09370396, 0.33074135, 0.29936931, 0.64351947,
       0.29848002, 0.08012629, 0.5567792 , 0.02322294, 2.54021909,
       0.19414214, 2.67043015, 1.35934642, 0.04421984, 2.49579754,
       0.33854536, 0.82877641, 0.19434373, 0.30614896, 2.25904764])

In [ ]:
# Amostra Aleatória: Exponencial(1/0.5)
np.random.exponential(scale=0.5, size=20)

array([0.10747112, 0.11385818, 0.76756233, 0.00675015, 0.30343404,
       0.39013189, 0.77907161, 0.14556523, 0.0575554 , 2.11766915,
       0.27547976, 0.00912788, 0.73347233, 0.29492124, 0.33201394,
       0.51358466, 0.54363421, 0.17599209, 0.47099521, 0.42578916])

In [ ]:
# Amostra Aleatória: Exponencial(0.5)
np.random.exponential(scale=1/0.5, size=20)

array([0.96946934, 1.74849498, 4.34500173, 1.76504485, 1.20363194,
       0.24273276, 2.71138199, 2.50572097, 0.50371676, 2.65980459,
       2.25417599, 0.19569661, 0.74685219, 3.04301664, 7.73609644,
       1.04332269, 1.59718689, 1.20552356, 1.08070688, 1.67975869])

In [ ]:
# Amostra Aleatória: Weibull(2, 1)
np.random.weibull(a=2, size=20)

array([0.75400382, 0.12505814, 1.79697985, 0.88696741, 0.96842009,
       1.07723056, 0.74660197, 0.21005428, 0.62252463, 0.37113267,
       0.96002824, 0.97028888, 0.96484582, 0.92268036, 0.61320348,
       1.67022078, 0.41139082, 0.76169539, 0.92755198, 1.50796011])

In [ ]:
# Amostra Aleatória: Weibull(2, 2)
2 * np.random.weibull(a=2, size=20)

array([2.14210011, 2.69864793, 1.01853213, 2.89162695, 2.88500291,
       0.37061154, 1.01627722, 1.78193659, 0.16692618, 1.73338251,
       0.90504195, 2.7303208 , 2.37826152, 1.74244992, 0.67489661,
       2.15345466, 2.51836682, 2.5231784 , 0.38379796, 2.32899507])

- Como garantir a replicabilidade do meu projeto?

In [ ]:
# Amostra Aleatória: Normal(0, 1)
np.random.normal(loc=0, scale=1, size=10)

array([-0.94955021, -0.44264835, -0.21249692, -0.86922292,  0.14614435,
        2.28374079,  0.43740325, -0.15207782, -0.98589807, -1.45088776])

In [ ]:
# Amostra Aleatória: Normal(0, 1)
np.random.normal(loc=0, scale=1, size=10)

array([-0.3112631 , -1.34407758,  1.96744367, -0.79436195,  2.28797817,
       -0.24232073, -0.90403555,  0.4510377 , -0.12063104,  0.77943502])

In [ ]:
# Defini-se estado aleatório (semente)
np.random.seed(123456789)

# Amostra Aleatória: Normal(0, 1)
array_norm = np.random.normal(loc=0, scale=1, size=10)

# Visualizar
array_norm

array([ 2.212902  ,  2.1283978 ,  1.8417114 ,  0.08238248,  0.85896368,
       -0.82601643,  1.15727052,  1.37591514,  0.94302846,  0.8478706 ])

## (1.4) Operações Matemáticas, Lógicas e Estatísticas

### (1.4.1) Operações Matemáticas

In [ ]:
# Definindo arrays
a = np.arange(0, 12, 2).reshape(2, 3)
b = np.arange(1, 12, 2).reshape(2, 3)

# Visualizando arrays
print(a)
print()
print(b)

[[ 0  2  4]
 [ 6  8 10]]

[[ 1  3  5]
 [ 7  9 11]]


- Operações aritimética com arrays: elemento a elemento

In [ ]:
# Soma
soma_matrix = a + b
print(soma_matrix)
print()

# Subtração
diff_matrix = a - b
print(diff_matrix)
print()

# Multiplicação
mult_matrix = a * b
print(mult_matrix)
print()

# Divisão
div_matrix = a / b
print(div_matrix)
print()

# Potenciação
exp_matrix = a ** b
print(exp_matrix)

[[ 1  5  9]
 [13 17 21]]

[[-1 -1 -1]
 [-1 -1 -1]]

[[  0   6  20]
 [ 42  72 110]]

[[0.         0.66666667 0.8       ]
 [0.85714286 0.88888889 0.90909091]]

[[           0            8         1024]
 [      279936    134217728 100000000000]]


In [ ]:
# Imprime a soma de a e b
print(np.add(a, b))
print()

# Imprime a diferença entre a e b
print(np.subtract(a, b))
print()

# Imprime o produto de a e b
print(np.multiply(a, b))
print()

# Imprime o quociente de a e b
print(np.divide(a, b))
print()

# Imprime a por b elevado à potência de b
print(np.power(a, b))

[[ 1  5  9]
 [13 17 21]]

[[-1 -1 -1]
 [-1 -1 -1]]

[[  0   6  20]
 [ 42  72 110]]

[[0.         0.66666667 0.8       ]
 [0.85714286 0.88888889 0.90909091]]

[[           0            8         1024]
 [      279936    134217728 100000000000]]


In [ ]:
# Operando uma matriz por um escalar
print("Matriz original:\n", a)
print("\nSomando 1 a cada elemento:\n", 1 + a)
print("\nMultiplicando cada elemento por 2:\n", 2 * a)
print("\nCalculando 1 + (2 * a) para cada elemento:\n", 1 + (2 * a))

Matriz original:
 [[ 0  2  4]
 [ 6  8 10]]

Somando 1 a cada elemento:
 [[ 1  3  5]
 [ 7  9 11]]

Multiplicando cada elemento por 2:
 [[ 0  4  8]
 [12 16 20]]

Calculando 1 + (2 * a) para cada elemento:
 [[ 1  5  9]
 [13 17 21]]


- Operações não lineares com arrays


In [ ]:
print("Matriz original:\n", b)
print("\nRaiz Quadrada:\n", np.sqrt(b))
print("\nExponencial:\n", np.exp(b))
print("\nLogaritmo Natural:\n", np.log(b))
print("\nSeno:\n", np.sin(b))
print("\nCosseno:\n", np.cos(b))
print("\nTangente:\n", np.tan(b))

Matriz original:
 [[ 1  3  5]
 [ 7  9 11]]

Raiz Quadrada:
 [[1.         1.73205081 2.23606798]
 [2.64575131 3.         3.31662479]]

Exponencial:
 [[2.71828183e+00 2.00855369e+01 1.48413159e+02]
 [1.09663316e+03 8.10308393e+03 5.98741417e+04]]

Logaritmo Natural:
 [[0.         1.09861229 1.60943791]
 [1.94591015 2.19722458 2.39789527]]

Seno:
 [[ 0.84147098  0.14112001 -0.95892427]
 [ 0.6569866   0.41211849 -0.99999021]]

Cosseno:
 [[ 0.54030231 -0.9899925   0.28366219]
 [ 0.75390225 -0.91113026  0.0044257 ]]

Tangente:
 [[ 1.55740772e+00 -1.42546543e-01 -3.38051501e+00]
 [ 8.71447983e-01 -4.52315659e-01 -2.25950846e+02]]


- Operações de álgebra linear para `arrays`

In [ ]:
# Definição de array
arr1 = np.full(shape=(2, 2), fill_value=2)

# Visualização
arr1

array([[2, 2],
       [2, 2]])

In [ ]:
# Definição de array
arr2 = np.arange(4).reshape(2, 2)

# Visualização
arr2

array([[0, 1],
       [2, 3]])

In [ ]:
# Definição de array
arr3 = np.array([
    [1, 35, 1/3],
    [3, 10, -1],
    [1/3, -1, 1e-10]
])

# Visualização
arr3

array([[ 1.00000000e+00,  3.50000000e+01,  3.33333333e-01],
       [ 3.00000000e+00,  1.00000000e+01, -1.00000000e+00],
       [ 3.33333333e-01, -1.00000000e+00,  1.00000000e-10]])

In [ ]:
# Definição de array
arr4 = np.array([
    [29, 64, 1/25],
    [3, 10, -np.sqrt(2654)],
    [1/3, -1e+10, 1e-100]
])

# Visualização
arr4

array([[ 2.90000000e+001,  6.40000000e+001,  4.00000000e-002],
       [ 3.00000000e+000,  1.00000000e+001, -5.15169875e+001],
       [ 3.33333333e-001, -1.00000000e+010,  1.00000000e-100]])

In [ ]:
# Determiante
np.linalg.det(arr1)

np.float64(0.0)

In [ ]:
# Determiante
np.linalg.det(arr2)

np.float64(-2.0)

In [ ]:
# Determinante
np.linalg.det(arr3)

np.float64(-14.777777787277778)

In [ ]:
# Determinante
np.linalg.det(arr4)

np.float64(-14941126373073.02)

In [ ]:
# Transposta
for arr in [arr1, arr2, arr3, arr4]:
  print(np.transpose(arr))
  print()

[[2 2]
 [2 2]]

[[0 2]
 [1 3]]

[[ 1.00000000e+00  3.00000000e+00  3.33333333e-01]
 [ 3.50000000e+01  1.00000000e+01 -1.00000000e+00]
 [ 3.33333333e-01 -1.00000000e+00  1.00000000e-10]]

[[ 2.90000000e+001  3.00000000e+000  3.33333333e-001]
 [ 6.40000000e+001  1.00000000e+001 -1.00000000e+010]
 [ 4.00000000e-002 -5.15169875e+001  1.00000000e-100]]



In [ ]:
# Inversa
for arr in [arr2, arr3, arr4]:
  print(np.linalg.inv(arr))
  print()

[[-1.5  0.5]
 [ 1.   0. ]]

[[ 0.06766917  0.02255639  2.59398496]
 [ 0.02255639  0.0075188  -0.13533835]
 [ 0.42857143 -0.85714286  6.42857142]]

[[ 3.44799891e-02  2.67717433e-05  2.20698702e-10]
 [ 1.14933297e-12  8.92391444e-16 -1.00000000e-10]
 [ 2.00788075e-03 -1.94095139e-02 -6.55907711e-12]]



> **Nota:** Para mais funções de Álgebra linear: [`np.linalg`](https://numpy.org/doc/stable/reference/routines.linalg.html)

### (1.4.2) Operações Lógicas

In [ ]:
# Definindo array
arr = np.arange(0, 21).reshape(3, 7)

# Visualizar
arr

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

* `np.where(condição_booleana, valores_para_condição_verdadeira, valores_para_condição_falsa)`

* `np.logical_and(array_one, array_two)`: Se `array_one` **E** `array_two` forem verdadeiro, o resultado é verdadeiro.

* `np.logical_or(array_one, array_two)`: Se `array_one` **OU** `array_two` forem verdadeiro, o resultado é verdadeiro.

In [ ]:
# Modificando com base em operação booleana
arr_modif = np.where(arr % 2 == 0, "par", "ímpar")

# Visualizar
arr_modif

array([['par', 'ímpar', 'par', 'ímpar', 'par', 'ímpar', 'par'],
       ['ímpar', 'par', 'ímpar', 'par', 'ímpar', 'par', 'ímpar'],
       ['par', 'ímpar', 'par', 'ímpar', 'par', 'ímpar', 'par']],
      dtype='<U5')

In [ ]:
# Definindo arrays
array_one = np.array([True, False, True])
array_two = np.array([False, True, True])

# Imprimindo comparação
print(np.logical_and(a, b))
print()
print(np.logical_or(a, b))

[[False  True  True]
 [ True  True  True]]

[[ True  True  True]
 [ True  True  True]]


In [ ]:
# Imprimindo comparação
print(np.logical_and(arr % 2 == 0, arr % 4 == 0))
print()
print(np.logical_or(arr % 2 == 0, arr % 4 == 0))

[[ True False False False  True False False]
 [False  True False False False  True False]
 [False False  True False False False  True]]

[[ True False  True False  True False  True]
 [False  True False  True False  True False]
 [ True False  True False  True False  True]]


### (1.4.3) Operações Estatísticas

In [ ]:
# Definindo array
array_data = np.arange(1, 11)

# Embalhando os dados
np.random.shuffle(array_data)

# Visualizar
array_data

array([ 8, 10,  5,  9,  7,  1,  3,  4,  2,  6])

In [ ]:
# Calculando as Estatísticas de Ordem
print(f"Mínimo: {np.min(array_data)}")
print(f"Q1 (25%): {np.quantile(array_data, 0.25)}")
print(f"Q2 (50%): {np.quantile(array_data, 0.50)}")
print(f"Q3 (75%): {np.quantile(array_data, 0.75)}")
print(f"Máximo: {np.max(array_data)}")

Mínimo: 1
Q1 (25%): 3.25
Q2 (50%): 5.5
Q3 (75%): 7.75
Máximo: 10


In [ ]:
# Calculando Medidas de Tendência Central
print("Média:", np.mean(array_data))
print("Mediana:", np.median(array_data))

Média: 5.5
Mediana: 5.5


In [ ]:
# Calculando Medidas de Variabilidade
print("Desvio padrão:", np.std(array_data))
print("Variância:", np.var(array_data))
print(f"Amplitude Total: {np.max(array_data) - np.min(array_data)}")

Desvio padrão: 2.8722813232690143
Variância: 8.25
Amplitude Total: 9


In [ ]:
# Outras medidas
print("Dados ordenados:", np.sort(array_data))
print(f"Tamanho da Amostra: {len(array_data)}")
print("Soma total:", np.sum(array_data))

Dados ordenados: [ 1  2  3  4  5  6  7  8  9 10]
Tamanho da Amostra: 10
Soma total: 55


In [ ]:
# Defini-se estado aleatório (semente)
np.random.seed(123456789)

# Definido arrays
arr1 = np.random.randint(low=5, high=15, size=25)
arr2 = np.random.rand(25) * 100

# Visualizar
print(arr1)
print()
print(arr2)

[13  7 14 12  9  8  9  5  8  9  7  9 10  6  8 13 12 10 14  5 10  8  5  5
  8]

[40.66554425 98.02586037 54.20651799 24.22946119 25.22416821 56.51557864
 13.33368799 87.62585589 48.0331855  28.3325868  89.22107811 82.76319705
 97.99704702 86.72329719 19.3505653  45.44906731 80.51827816 74.72314167
 91.99597185 22.04699297 99.7953098  60.27965203  3.55184574 55.55210785
 31.96425219]


Considere `arr1` como tempo de serviço e `arr2` como salário. Qual o grau de dependência entre eles?

In [ ]:
# Matriz de Covariâncias
np.cov(arr1, arr2)

array([[  7.87333333,   8.04334875],
       [  8.04334875, 926.87999914]])

In [ ]:
# Matriz de Correlações
np.corrcoef(arr1, arr2)

array([[1.        , 0.09415553],
       [0.09415553, 1.        ]])

In [ ]:
# Defini-se estado aleatório (semente)
np.random.seed(123456789)

# Definido arrays
arr1 = np.random.randint(low=5, high=15, size=25)
arr2 = 2.5 * arr1 + np.random.normal(loc=0, scale=10, size=25)

# Visualizar
print(arr1)
print()
print(arr2)

[13  7 14 12  9  8  9  5  8  9  7  9 10  6  8 13 12 10 14  5 10  8  5  5
  8]

[35.39492156 16.93733403 19.0904603  32.59690981 26.65963394  4.18277233
  4.33068236 10.85071787 17.96803779  8.81522433 23.68565475 30.13558025
 25.61256487  9.87536839 20.23564359 12.30633438 50.5862978  29.195676
 25.20784859 11.45271441 33.70079148 27.03946018 14.09027327 10.81570894
  4.13313471]


In [ ]:
# Matriz de Covariâncias
np.cov(arr1, arr2)

array([[  7.87333333,  16.55343433],
       [ 16.55343433, 133.16929709]])

In [ ]:
# Matriz de Correlações
np.corrcoef(arr1, arr2)

array([[1.        , 0.51121871],
       [0.51121871, 1.        ]])

Mas e se o `array` que eu estou lidando não for numérico?

In [ ]:
# Defini-se estado aleatório (semente)
np.random.seed(123456789)

# Definindo array
arr = np.random.binomial(n=1, p=2/3, size=25)

# Visualizar
print(f"Amostra Aleatória de uma Bernoulli(2/3):\n{arr}")

# Modificando para uma melhor visualização
arr_modif = np.where(arr == 1, "coroa", "cara")

# Visualizar
print(f"\nAmostra Aleatória de uma Bernoulli(2/3) modificada:\n{arr_modif}")

Amostra Aleatória de uma Bernoulli(2/3):
[1 1 1 0 1 0 0 1 0 1 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0]

Amostra Aleatória de uma Bernoulli(2/3) modificada:
['coroa' 'coroa' 'coroa' 'cara' 'coroa' 'cara' 'cara' 'coroa' 'cara'
 'coroa' 'cara' 'cara' 'cara' 'coroa' 'coroa' 'coroa' 'coroa' 'coroa'
 'coroa' 'cara' 'coroa' 'cara' 'coroa' 'coroa' 'cara']


In [ ]:
# Quais valores únicos?
np.unique(arr_modif)

array(['cara', 'coroa'], dtype='<U5')

In [ ]:
# Frequência dessas valores?
np.bincount(arr)

array([10, 15])

In [ ]:
# Quais valores únicos e suas frequências?
np.unique(arr_modif, return_counts=True)

(array(['cara', 'coroa'], dtype='<U5'), array([10, 15]))