# (1) Numpy

O NumPy é uma biblioteca fundamental para a computação científica em Python, especialmente quando se trabalha com grandes conjuntos de dados numéricos. Ele oferece uma série de vantagens que o tornam uma ferramenta indispensável para diversos campos, como:

1. ***Eficiência em cálculos numéricos:***

  - **Arrays:** O NumPy introduz o conceito de arrays, que são estruturas de dados homogêneas (todos os elementos têm o mesmo tipo de dado) e multidimensionais. Eles são muito mais eficientes em termos de memória e velocidade de processamento do que as listas padrão do Python.
  - **Vetorização:** O NumPy permite realizar operações matemáticas em arrays inteiros de uma só vez, eliminando a necessidade de loops explícitos. Isso resulta em um código mais conciso e eficiente.

2. ***Ampla variedade de funções:***

  - **Matemáticas:** O NumPy oferece uma vasta gama de funções matemáticas, como trigonometria, álgebra linear, estatística e geração de números aleatórios.
  - **Manipulação de arrays:** Ele fornece ferramentas poderosas para criar, modificar e manipular arrays, como indexação, fatiamento, ordenação e redimensionamento.

3. ***Integração com outras bibliotecas de grande importância em Análise de Dados:***

  - **SciPy:** O NumPy serve como base para a biblioteca SciPy, que oferece algoritmos mais avançados para otimização, processamento de sinais, estatística e muito mais.
  - **Pandas:** O Pandas, utilizado para análise de dados, é construído sobre o NumPy e oferece estruturas de dados mais flexíveis para trabalhar com dados tabulares.
  - **Scikit-learn:** Essa biblioteca de machine learning utiliza o NumPy para representar dados e realizar cálculos numéricos.

4. ***Comunidade e recursos:***

  - **Grande comunidade:** O NumPy possui uma comunidade ativa de desenvolvedores e usuários, o que significa que você encontrará muitos recursos, tutoriais e exemplos online.
  - **Documentação completa:** A documentação oficial do NumPy é extensa e bem detalhada, cobrindo todos os aspectos da biblioteca.

5. ***Em resumo, o NumPy é fundamental para:***

  - **Ciência de dados:** Análise de dados, machine learning, deep learning
  - **Engenharia:** Simulação, processamento de sinais, otimização
  - **Finanças:** Modelagem financeira, análise de séries temporais
  - **Visualização de dados:** Criação de gráficos e visualizações

5. ***Quando usar NumPy:***

  - **Grandes conjuntos de dados numéricos:** O NumPy é ideal para trabalhar com matrizes e vetores de grandes dimensões.
  - **Operações matemáticas complexas:** Ele oferece um conjunto completo de funções para realizar cálculos numéricos de forma eficiente.
  - **Desempenho:** Se a velocidade de execução for crucial para sua aplicação, o NumPy é a escolha certa.

## (1.1) Primeiros passos - Definição de um `array`

In [151]:
# Importe a biblioteca `numpy` apelidando ela de `np`
import numpy as np

**O que são Arrays?**
Imagine uma lista de números, como `[1, 2, 3, 4]`. Essa é a ideia básica de um array unidimensional. Um array é uma estrutura de dados que armazena uma coleção de elementos do mesmo tipo. Esses elementos podem ser números, strings, ou até mesmo outros arrays.

In [152]:
# Criando uma lista
my_list = [1, 2, 3, 4, 5, 6]

# Convertendo a lista para um array NumPy
vector = np.array(my_list)

# Visualizando array unidimensional
vector

array([1, 2, 3, 4, 5, 6])

In [153]:
# Criando duas listas
list_one = my_list[:3] # Linha 1 (array unidimensional)
list_two = my_list[3:] # Linha 2 (array unidimensional)

# Convertendo as listas para arrays NumPy
matrix = np.array([list_one, list_two])

# Visualizando array multidimensional
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [154]:
# Veja, agora, o tipo de dado que está sendo trabalhado
print(type(vector))
print(type(matrix))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### (1.1.1) Formas práticas de criar um array

1. `np.zeros()`

In [155]:
# Array unidimensional
np.zeros(shape=10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [156]:
# Array unidimensional
np.zeros(shape=10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [157]:
# Array multidimensional
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [158]:
# Array multidimensional
np.zeros(shape=(3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [159]:
# Array multidimensional
np.zeros(shape=(10, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [160]:
# Array multidimensional
np.zeros(shape=(10, 1), dtype=int)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

2. `np.ones()`

In [161]:
# Array unidimensional
np.ones(shape=10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [162]:
# Array unidimensional
np.ones(shape=10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [163]:
# Array multidimensional
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [164]:
# Array multidimensional
np.ones(shape=(3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [165]:
# Array multidimensional
np.ones(shape=(10, 1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [166]:
# Array multidimensional
np.ones(shape=(10, 1), dtype=int)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

3. `np.full()`

In [167]:
# Array multidimensional
np.full(shape=(2, 3), fill_value=1/2)

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

4. `np.eye()`

In [168]:
# Array multidimensional
np.eye(N=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [169]:
# Array multidimensional
np.eye(N=3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [170]:
# Array multidimensional
np.eye(N=3, M=4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

5. `np.arange()` e `np.linspace()`

In [171]:
# Array unidimensional
np.arange(start=0, stop=10, step=2)

array([0, 2, 4, 6, 8])

In [172]:
# Array unidimensional
np.arange(start=-12, stop=0, step=2)

array([-12, -10,  -8,  -6,  -4,  -2])

In [173]:
# Array unidimensional
np.linspace(start=0, stop=10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [174]:
# Array unidimensional
np.linspace(start=0, stop=10, num=5, dtype=int)

array([ 0,  2,  5,  7, 10])

In [175]:
# Array unidimensional
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [176]:
# Array unidimensional
np.linspace(1, 10, 10, dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [177]:
# Array unidimensional
np.linspace(start=-4, stop=4, num=1000)

array([-4.        , -3.99199199, -3.98398398, -3.97597598, -3.96796797,
       -3.95995996, -3.95195195, -3.94394394, -3.93593594, -3.92792793,
       -3.91991992, -3.91191191, -3.9039039 , -3.8958959 , -3.88788789,
       -3.87987988, -3.87187187, -3.86386386, -3.85585586, -3.84784785,
       -3.83983984, -3.83183183, -3.82382382, -3.81581582, -3.80780781,
       -3.7997998 , -3.79179179, -3.78378378, -3.77577578, -3.76776777,
       -3.75975976, -3.75175175, -3.74374374, -3.73573574, -3.72772773,
       -3.71971972, -3.71171171, -3.7037037 , -3.6956957 , -3.68768769,
       -3.67967968, -3.67167167, -3.66366366, -3.65565566, -3.64764765,
       -3.63963964, -3.63163163, -3.62362362, -3.61561562, -3.60760761,
       -3.5995996 , -3.59159159, -3.58358358, -3.57557558, -3.56756757,
       -3.55955956, -3.55155155, -3.54354354, -3.53553554, -3.52752753,
       -3.51951952, -3.51151151, -3.5035035 , -3.4954955 , -3.48748749,
       -3.47947948, -3.47147147, -3.46346346, -3.45545546, -3.44

### (1.1.2) Atributos de `array`

In [178]:
# Acessando os atributos
print("Shape:", vector.shape)
print("Dtype:", vector.dtype)
print("Ndim:", vector.ndim)
print("Size:", vector.size)
print()
print(vector)

Shape: (6,)
Dtype: int32
Ndim: 1
Size: 6

[1 2 3 4 5 6]


In [179]:
# Acessando os atributos
print("Shape:", matrix.shape)
print("Dtype:", matrix.dtype)
print("Ndim:", matrix.ndim)
print("Size:", matrix.size)
print()
print(matrix)

Shape: (2, 3)
Dtype: int32
Ndim: 2
Size: 6

[[1 2 3]
 [4 5 6]]


## (1.2) Indexação, Fatiamento e Manipulação de `array`

In [180]:
# Definição de um array
arr1 = np.array([2, 1, 5, 3, 7, 4, 6, 8])

# Visualização
arr1

array([2, 1, 5, 3, 7, 4, 6, 8])

In [181]:
# Definição de um array
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Visualização
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [182]:
# Definição de um array
arr3 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Visualização
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

-  Comandos para Indexação e Fatiamento:

In [183]:
arr1[0] # Acessar elementos específicos: array[índice]

2

In [184]:
arr1[0:2] # Fatiamento de arrays (arrays unidimensionais e multidimensionais): array[início:fim]

array([2, 1])

In [185]:
arr2[:, 2] # Seleção de linhas e colunas em arrays 2D: array[select_row, select_column]

array([3, 6, 9])

In [186]:
arr2[2, :] # Seleção de linhas e colunas em arrays 2D: array[select_row, select_column]

array([7, 8, 9])

-  Comandos para Indexação e Fatiamento Booleano:

In [188]:
arr3 >= 5

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [189]:
# Condição
five_up = arr3 >= 5

# Fatiando conforme a condição
arr3[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [190]:
arr3 % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [191]:
# Elementos pares
divisible_by_2 = arr3[arr3 % 2 == 0]

# Visualização
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

In [192]:
# Elementos maiores que 2 e menores que 11
(arr3 > 2) & (arr3 < 11)

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

In [193]:
# Condição dupla
c = arr3[(arr3 > 2) & (arr3 < 11)]

# Visualização
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [194]:
# Condição tripla
c = arr3[(arr3 > 2) & (arr3 < 11) & (arr3 % 2 == 0)]

# Visualização
c

array([ 4,  6,  8, 10])

- Manipulação da *forma* de `array` e concatenação de `arrays`:

In [195]:
# Definindo array
v1 = np.arange(6)

# Visualizar
v1

array([0, 1, 2, 3, 4, 5])

In [196]:
# Alterar a forma de v1
v2 = v1.reshape(2, 3)

# Visualizar
v2

array([[0, 1, 2],
       [3, 4, 5]])

In [197]:
# Alterar a forma de v1
v3 = v1.reshape(3, 2)

# Visualizar
v3

array([[0, 1],
       [2, 3],
       [4, 5]])

In [198]:
# Alterar a forma de v1
v4 = v1.reshape(v1.size, 1)

# Visualizar
v4

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [206]:
# Vetor Linha
row_vector = v1[np.newaxis, :]

# Visualizar
row_vector

array([[0, 1, 2, 3, 4, 5]])

In [69]:
# Vetor Coluna
col_vector = v1[:, np.newaxis]

# Visualizar
col_vector

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [207]:
print(f"Forma de v1: {v1.shape}")
print(f"Forma de v2: {v2.shape}")
print(f"Forma de v3: {v3.shape}")
print(f"Forma de v4: {v4.shape}")
print(f"Forma de row_vector: {row_vector.shape}")
print(f"Forma de col_vector: {col_vector.shape}")

Forma de v1: (6,)
Forma de v2: (2, 3)
Forma de v3: (3, 2)
Forma de v4: (6, 1)
Forma de row_vector: (1, 6)
Forma de col_vector: (6, 1)


In [211]:
# Considere o array
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Visualizar
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [212]:
# Usando a função np.ravel()
array_ravel = np.ravel(matrix, order="C")

# Visualizando
array_ravel

array([1, 2, 3, 4, 5, 6])

In [213]:
# Usando a função np.ravel()
array_ravel = np.ravel(matrix, order="F")

# Visualizando
array_ravel

array([1, 4, 2, 5, 3, 6])

In [214]:
# Usando o método array.flatten()
array_flatten = matrix.flatten(order="C")

# Visualizando
array_flatten

array([1, 2, 3, 4, 5, 6])

In [215]:
# Usando o método array.flatten()
array_flatten = matrix.flatten(order="F")

# Visualizando
array_flatten

array([1, 4, 2, 5, 3, 6])

- Alterando o tipo dos elementos do `array`

In [216]:
# Modificando para um array de pontos flutuantes
array_flatten.astype(np.float64)

array([1., 4., 2., 5., 3., 6.])

In [217]:
# Modificando para um array de pontos flutuantes
np.array(array_flatten, dtype=np.float64)

array([1., 4., 2., 5., 3., 6.])

In [218]:
# Definindo um array de zeros
array_zeros = np.zeros(shape=(3, 3))

# Visualizar o array de zeros
print(array_zeros)

# Iterar pelas linhas do array
for i in range(1, array_zeros.shape[0] + 1):
  # Iterar pelas colunas do array
  for j in range(1, array_zeros.shape[1] + 1):
    # Preencher o array com o valor da divisão de i por j
    array_zeros[i - 1, j - 1] = i / j

# Visualizar o array preenchido
print("\n", array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[1.         0.5        0.33333333]
 [2.         1.         0.66666667]
 [3.         1.5        1.        ]]


In [219]:
# Modificando para um array de inteiros
np.array(array_zeros, dtype=np.int64)

array([[1, 0, 0],
       [2, 1, 0],
       [3, 1, 1]], dtype=int64)

In [220]:
# Modificando para um array de inteiros
array_zeros.astype(np.int64)

array([[1, 0, 0],
       [2, 1, 0],
       [3, 1, 1]], dtype=int64)

- Concateção de `arrays`:

In [221]:
# Definindo arrays para exemplo de concatenação
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [227]:
# Concatenando verticalmente (ao longo do eixo 0)
c1 = np.concatenate((a, b), axis=0)

# Visualizar
c1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [228]:
# Concatenando horizontalmente (ao longo do eixo 1)
d1 = np.concatenate((a, b.T), axis=1)

# Visualizar
d1

array([[1, 2, 5],
       [3, 4, 6]])

In [229]:
print(b)   # array original
print()
print(b.T) # array transposto

[[5 6]]

[[5]
 [6]]


In [85]:
# Concatenando verticalmente
c2 = np.vstack((a, b))

# Visualizar
c2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [86]:
# Comparação
c1 == c2

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [231]:
# Concatenando horizontalmente
d2 = np.hstack((a, b.T))

# Visualizar
d2

array([[1, 2, 5],
       [3, 4, 6]])

In [232]:
# Comparação
d1 == d2

array([[ True,  True,  True],
       [ True,  True,  True]])

## (1.3) Geração de arrays aleatórios

1. Comandos iniciais para geração de arrays aleatórios

In [233]:
# Array multidimensional uniformimente distribuído
np.random.rand(3, 2)

array([[0.54206518, 0.24229461],
       [0.25224168, 0.56515579],
       [0.13333688, 0.87625856]])

In [234]:
# Array multidimensional uniformimente distribuído
np.random.rand(10, 1)

array([[0.48033186],
       [0.28332587],
       [0.89221078],
       [0.82763197],
       [0.97997047],
       [0.86723297],
       [0.19350565],
       [0.45449067],
       [0.80518278],
       [0.74723142]])

In [235]:
# Array unidimensional uniformimente distribuído
np.random.rand(10)

array([0.91995972, 0.22046993, 0.9979531 , 0.60279652, 0.03551846,
       0.55552108, 0.31964252, 0.50210462, 0.53312172, 0.66251339])

In [236]:
# Array multidimensional uniformimente distribuído
np.random.rand(3, 4)

array([[0.45827568, 0.10987638, 0.72993767, 0.78420357],
       [0.14128971, 0.83868694, 0.40272632, 0.40642366],
       [0.37066631, 0.91701562, 0.49067937, 0.96598837]])

In [243]:
# Array multidimensional uniformimente distribuído
np.random.rand(3, 2)

array([[0.40892395, 0.34782068],
       [0.16887992, 0.08981502],
       [0.30551554, 0.38535222]])

In [241]:
# Números aleatórios dentro de um intervalo
np.random.randint(low=0, high=10, size=10)

array([7, 0, 4, 4, 7, 4, 2, 1, 7, 1])

In [244]:
# Números aleatórios dentro de um intervalo
np.random.randint(low=0, high=10, size=(10, 1))

array([[0],
       [9],
       [7],
       [4],
       [5],
       [8],
       [1],
       [6],
       [7],
       [6]])

In [245]:
# Números (inteiros) aleatórios dentro de um intervalo
np.random.randint(low=0, high=10, size=(5, 2))

array([[6, 0],
       [0, 2],
       [2, 4],
       [0, 7],
       [1, 5]])

1. Simulando algumas distribuições de probabilidade

In [247]:
# Amostra Aleatória: Uniforme(0, 1)
np.random.uniform(low=0, high=1, size=20)

array([0.93420173, 0.78310307, 0.04077077, 0.31062887, 0.11716744,
       0.92161265, 0.19714855, 0.79319511, 0.19555856, 0.85263614,
       0.66167279, 0.78240023, 0.66559923, 0.54845381, 0.56583245,
       0.65930704, 0.10348994, 0.85850943, 0.54240032, 0.02047965])

In [248]:
# Amostra Aleatória: Uniforme(0, 2)
np.random.uniform(low=0, high=2, size=20)

array([0.37613979, 1.64643227, 0.36987326, 0.44561089, 0.59069773,
       0.89717551, 0.91400748, 0.68141133, 0.52287259, 1.07654748,
       1.25139345, 0.73805758, 0.14951255, 1.77962913, 0.75224713,
       0.69794878, 0.98492698, 0.58222726, 1.11051277, 0.43661601])

In [249]:
# Amostra Aleatória: Uniforme(1, 2)
np.random.uniform(low=1, high=2, size=20)

array([1.73748785, 1.49646417, 1.88161679, 1.69550814, 1.69091362,
       1.00099285, 1.587711  , 1.10587287, 1.61625415, 1.2327503 ,
       1.0185662 , 1.56386391, 1.9558084 , 1.97960742, 1.5542382 ,
       1.12747751, 1.88691997, 1.9784939 , 1.53251661, 1.32027105])

In [250]:
# Amostra Aleatória: Normal(0, 1)
np.random.normal(loc=0, scale=1, size=20)

array([-1.12565211,  0.66943458, -0.75705499,  0.03810079, -1.08369959,
        0.51684037,  0.10531938,  0.2371225 , -0.37470391, -0.02138017,
        1.18407295,  0.92211   , -0.37653009, -0.74361059,  0.56097838,
       -1.72823533, -0.25624445, -1.19512593, -0.62864691, -0.7745082 ])

In [251]:
# Amostra Aleatória: Normal(5, 1)
np.random.normal(loc=5, scale=1, size=20)

array([4.52022764, 5.05668804, 3.39388952, 6.8280577 , 6.24427951,
       4.71374694, 7.2126958 , 5.25746445, 3.81805754, 5.53859584,
       5.78208174, 6.45556216, 5.48205834, 5.2162848 , 3.4719395 ,
       4.97967769, 5.0537519 , 7.10164   , 5.07009274, 4.50703806])

In [252]:
# Amostra Aleatória: Normal(-5, 1)
np.random.normal(loc=-5, scale=1, size=20)

array([-3.72087644, -4.87062854, -5.65262853, -3.96289079, -4.23167309,
       -4.69319629, -6.2890283 , -5.63954396, -3.98975395, -5.8147702 ,
       -4.56588151, -3.14758784, -4.34893246, -5.26004598, -4.65297927,
       -6.18194345, -6.39282225, -5.31821668, -4.11895489, -4.23918948])

In [103]:
# Amostra Aleatória: Bernoulli(0.5)
np.random.binomial(n=1, p=0.5, size=20)

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1])

In [253]:
# Amostra Aleatória: Binomial(10, 0.5)
np.random.binomial(n=10, p=0.5, size=20)

array([5, 3, 3, 5, 5, 5, 5, 3, 5, 2, 3, 4, 5, 4, 4, 6, 5, 5, 5, 2])

In [254]:
# Amostra Aleatória: X^2(5)
np.random.chisquare(df=5, size=20)

array([1.06392036, 5.77714384, 9.90254859, 3.55405431, 3.69210844,
       3.60030691, 1.87023485, 8.46967608, 3.45936809, 2.47313077,
       2.0239376 , 1.46340976, 4.50095772, 3.60036239, 5.23366949,
       3.40276356, 7.76970595, 8.25851618, 4.42094759, 1.94467428])

In [106]:
# Amostra Aleatória: X^2(10)
np.random.chisquare(df=10, size=20)

array([ 9.22693638,  7.83496067, 13.93435278,  7.82028216,  8.26748491,
        7.63472503, 14.9077603 , 18.44944339,  5.84584686, 15.95277418,
        9.60784246,  6.61421214, 10.80275187, 13.22036751,  6.25341065,
        8.04959881,  7.09162618, 19.72096652,  6.11390496, 10.05397996])

In [255]:
# Amostra Aleatória: F(1, 2)
np.random.f(dfnum=1, dfden=2, size=20)

array([6.76580401e-01, 1.74419661e-01, 3.23456403e-01, 2.40461062e+01,
       4.18616249e-01, 1.67151968e+00, 7.40774689e-01, 1.66198938e-01,
       4.09083042e-01, 1.12928144e+01, 8.29635468e+00, 6.08325968e-01,
       9.35435036e-05, 2.26954665e+00, 7.33688165e+00, 3.11332533e+00,
       9.93774827e-05, 6.85653807e-03, 1.23196213e+00, 1.17863688e+01])

In [256]:
# Amostra Aleatória: F(2, 3)
np.random.f(dfnum=2, dfden=3, size=20)

array([ 0.10194462,  2.22130683,  6.10508766,  0.3766903 , 11.85252189,
        0.52486591,  3.48562146,  3.06614267,  0.07433879,  0.11507371,
        2.87168528,  0.78168018,  0.50780727,  1.43954215,  1.79091682,
        0.40081411,  0.47643623,  0.37697366,  9.8366741 , 10.16786004])

In [109]:
# Amostra Aleatória: Exponencial(1)
np.random.exponential(scale=1, size=20)

array([0.0470508 , 0.38305739, 0.90973317, 0.63884757, 0.17735595,
       6.79886458, 1.0504845 , 0.58262137, 0.75094393, 2.71564485,
       1.27990062, 1.9120289 , 0.72054604, 0.07766124, 0.98686138,
       1.99662667, 0.27172181, 1.70528061, 0.34844531, 1.49932771])

In [110]:
# Amostra Aleatória: Exponencial(1/0.5)
np.random.exponential(scale=0.5, size=20)

array([0.63831098, 0.45973059, 0.27625379, 0.14210058, 0.6855583 ,
       0.16399062, 0.04546733, 0.48452174, 0.09194361, 0.07343129,
       1.527216  , 0.26894562, 0.59925402, 0.47715741, 0.72483344,
       0.84040696, 0.20012093, 0.10220036, 0.06604025, 0.8290231 ])

In [111]:
# Amostra Aleatória: Exponencial(0.5)
np.random.exponential(scale=1/0.5, size=20)

array([1.13230762, 9.39626794, 0.96334218, 1.79410279, 0.85288125,
       0.83798477, 2.68139912, 3.97663493, 0.9565282 , 2.26774815,
       0.5057015 , 0.39406914, 2.06671214, 0.48933233, 0.0428429 ,
       1.93352417, 0.10453701, 4.88958326, 2.36454656, 0.15799846])

In [258]:
# Amostra Aleatória: Weibull(2, 1)
np.random.weibull(a=2, size=20)

array([1.26464126, 1.08327564, 0.5917474 , 0.09181777, 1.07615314,
       1.15148636, 0.13488885, 1.37971044, 1.3780318 , 1.40322714,
       0.2243136 , 0.87207015, 0.44780609, 1.04706874, 0.50048123,
       0.30950582, 0.84893532, 1.7598291 , 1.11207694, 1.58233899])

In [259]:
# Amostra Aleatória: Weibull(2, 2)
2 * np.random.weibull(a=2, size=20)

array([2.4782386 , 1.99928449, 2.82905528, 2.72652124, 1.61731042,
       1.93922173, 0.54021989, 1.06837078, 1.73112323, 0.80893514,
       1.83695288, 1.83345339, 3.30527176, 2.30485459, 0.64185782,
       1.85062891, 1.15727301, 2.64582421, 2.81775515, 0.64242107])

- Como garantir a replicabilidade do meu projeto?

In [260]:
# Amostra Aleatória: Normal(0, 1)
np.random.normal(loc=0, scale=1, size=10)

array([-0.28408215,  0.12800382, -0.50981626, -0.73080212,  1.91229975,
       -1.05353716, -0.75988097, -1.66756969,  2.33767071,  0.01319848])

In [261]:
# Amostra Aleatória: Normal(0, 1)
np.random.normal(loc=0, scale=1, size=10)

array([ 1.15010566,  0.58883306, -1.47460278,  0.59146169, -1.13336771,
       -0.24601069,  0.71624457, -1.24560655,  1.92587891,  0.20617056])

In [269]:
# Defini-se estado aleatório (semente)
np.random.seed(123456789)

# Amostra Aleatória: Normal(0, 1)
array_norm = np.random.normal(loc=0, scale=1, size=10)

# Visualizar
array_norm

array([ 2.212902  ,  2.1283978 ,  1.8417114 ,  0.08238248,  0.85896368,
       -0.82601643,  1.15727052,  1.37591514,  0.94302846,  0.8478706 ])

## (1.4) Operações Matemáticas, Lógicas e Estatísticas

### (1.4.1) Operações Matemáticas

In [270]:
# Definindo arrays
a = np.arange(0, 12, 2).reshape(2, 3)
b = np.arange(1, 12, 2).reshape(2, 3)

# Visualizando arrays
print(a)
print()
print(b)

[[ 0  2  4]
 [ 6  8 10]]

[[ 1  3  5]
 [ 7  9 11]]


- Operações aritimética com arrays: elemento a elemento

In [271]:
# Soma
soma_matrix = a + b
print(soma_matrix)
print()

# Subtração
diff_matrix = a - b
print(diff_matrix)
print()

# Multiplicação
mult_matrix = a * b
print(mult_matrix)
print()

# Divisão
div_matrix = a / b
print(div_matrix)
print()

# Potenciação
exp_matrix = a ** b
print(exp_matrix)

[[ 1  5  9]
 [13 17 21]]

[[-1 -1 -1]
 [-1 -1 -1]]

[[  0   6  20]
 [ 42  72 110]]

[[0.         0.66666667 0.8       ]
 [0.85714286 0.88888889 0.90909091]]

[[         0          8       1024]
 [    279936  134217728 1215752192]]


In [272]:
# Imprime a soma de a e b
print(np.add(a, b))
print()

# Imprime a diferença entre a e b
print(np.subtract(a, b))
print()

# Imprime o produto de a e b
print(np.multiply(a, b))
print()

# Imprime o quociente de a e b
print(np.divide(a, b))
print()

# Imprime a por b elevado à potência de b
print(np.power(a, b))

[[ 1  5  9]
 [13 17 21]]

[[-1 -1 -1]
 [-1 -1 -1]]

[[  0   6  20]
 [ 42  72 110]]

[[0.         0.66666667 0.8       ]
 [0.85714286 0.88888889 0.90909091]]

[[         0          8       1024]
 [    279936  134217728 1215752192]]


In [273]:
# Operando uma matriz por um escalar
print("Matriz original:\n", a)
print("\nSomando 1 a cada elemento:\n", 1 + a)
print("\nMultiplicando cada elemento por 2:\n", 2 * a)
print("\nCalculando 1 + (2 * a) para cada elemento:\n", 1 + (2 * a))

Matriz original:
 [[ 0  2  4]
 [ 6  8 10]]

Somando 1 a cada elemento:
 [[ 1  3  5]
 [ 7  9 11]]

Multiplicando cada elemento por 2:
 [[ 0  4  8]
 [12 16 20]]

Calculando 1 + (2 * a) para cada elemento:
 [[ 1  5  9]
 [13 17 21]]


- Operações não lineares com arrays


In [274]:
print("Matriz original:\n", b)
print("\nRaiz Quadrada:\n", np.sqrt(b))
print("\nExponencial:\n", np.exp(b))
print("\nLogaritmo Natural:\n", np.log(b))
print("\nSeno:\n", np.sin(b))
print("\nCosseno:\n", np.cos(b))
print("\nTangente:\n", np.tan(b))

Matriz original:
 [[ 1  3  5]
 [ 7  9 11]]

Raiz Quadrada:
 [[1.         1.73205081 2.23606798]
 [2.64575131 3.         3.31662479]]

Exponencial:
 [[2.71828183e+00 2.00855369e+01 1.48413159e+02]
 [1.09663316e+03 8.10308393e+03 5.98741417e+04]]

Logaritmo Natural:
 [[0.         1.09861229 1.60943791]
 [1.94591015 2.19722458 2.39789527]]

Seno:
 [[ 0.84147098  0.14112001 -0.95892427]
 [ 0.6569866   0.41211849 -0.99999021]]

Cosseno:
 [[ 0.54030231 -0.9899925   0.28366219]
 [ 0.75390225 -0.91113026  0.0044257 ]]

Tangente:
 [[ 1.55740772e+00 -1.42546543e-01 -3.38051501e+00]
 [ 8.71447983e-01 -4.52315659e-01 -2.25950846e+02]]


- Operações de álgebra linear para `arrays`

In [275]:
# Definição de array
arr1 = np.full(shape=(2, 2), fill_value=2)

# Visualização
arr1

array([[2, 2],
       [2, 2]])

In [276]:
# Definição de array
arr2 = np.arange(4).reshape(2, 2)

# Visualização
arr2

array([[0, 1],
       [2, 3]])

In [277]:
# Definição de array
arr3 = np.array([
    [1, 35, 1/3],
    [3, 10, -1],
    [1/3, -1, 1e-10]
])

# Visualização
arr3

array([[ 1.00000000e+00,  3.50000000e+01,  3.33333333e-01],
       [ 3.00000000e+00,  1.00000000e+01, -1.00000000e+00],
       [ 3.33333333e-01, -1.00000000e+00,  1.00000000e-10]])

In [278]:
# Definição de array
arr4 = np.array([
    [29, 64, 1/25],
    [3, 10, -np.sqrt(2654)],
    [1/3, -1e+10, 1e-100]
])

# Visualização
arr4

array([[ 2.90000000e+001,  6.40000000e+001,  4.00000000e-002],
       [ 3.00000000e+000,  1.00000000e+001, -5.15169875e+001],
       [ 3.33333333e-001, -1.00000000e+010,  1.00000000e-100]])

In [279]:
# Determiante
np.linalg.det(arr1)

0.0

In [280]:
# Determiante
np.linalg.det(arr2)

-2.0

In [281]:
# Determinante
np.linalg.det(arr3)

-14.77777778727777

In [282]:
# Determinante
np.linalg.det(arr4)

-14941126373073.02

In [283]:
# Transposta
for arr in [arr1, arr2, arr3, arr4]:
  print(np.transpose(arr))
  print()

[[2 2]
 [2 2]]

[[0 2]
 [1 3]]

[[ 1.00000000e+00  3.00000000e+00  3.33333333e-01]
 [ 3.50000000e+01  1.00000000e+01 -1.00000000e+00]
 [ 3.33333333e-01 -1.00000000e+00  1.00000000e-10]]

[[ 2.90000000e+001  3.00000000e+000  3.33333333e-001]
 [ 6.40000000e+001  1.00000000e+001 -1.00000000e+010]
 [ 4.00000000e-002 -5.15169875e+001  1.00000000e-100]]



In [284]:
# Inversa
for arr in [arr2, arr3, arr4]:
  print(np.linalg.inv(arr))
  print()

[[-1.5  0.5]
 [ 1.   0. ]]

[[ 0.06766917  0.02255639  2.59398496]
 [ 0.02255639  0.0075188  -0.13533835]
 [ 0.42857143 -0.85714286  6.42857142]]

[[ 3.44799891e-02  2.67717433e-05  2.20698702e-10]
 [ 1.14933297e-12  8.92391444e-16 -1.00000000e-10]
 [ 2.00788075e-03 -1.94095139e-02 -6.55907711e-12]]



> **Nota:** Para mais funções de Álgebra linear: [`np.linalg`](https://numpy.org/doc/stable/reference/routines.linalg.html)

### (1.4.2) Operações Lógicas

In [285]:
# Definindo array
arr = np.arange(0, 21).reshape(3, 7)

# Visualizar
arr

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

* `np.where(condição_booleana, valores_para_condição_verdadeira, valores_para_condição_falsa)`

* `np.logical_and(array_one, array_two)`: Se `array_one` **E** `array_two` forem verdadeiro, o resultado é verdadeiro.

* `np.logical_or(array_one, array_two)`: Se `array_one` **OU** `array_two` forem verdadeiro, o resultado é verdadeiro.

In [286]:
# Modificando com base em operação booleana
arr_modif = np.where(arr % 2 == 0, "par", "ímpar")

# Visualizar
arr_modif

array([['par', 'ímpar', 'par', 'ímpar', 'par', 'ímpar', 'par'],
       ['ímpar', 'par', 'ímpar', 'par', 'ímpar', 'par', 'ímpar'],
       ['par', 'ímpar', 'par', 'ímpar', 'par', 'ímpar', 'par']],
      dtype='<U5')

In [287]:
# Definindo arrays
array_one = np.array([True, False, True])
array_two = np.array([False, True, True])

# Imprimindo comparação
print(np.logical_and(a, b))
print()
print(np.logical_or(a, b))

[[False  True  True]
 [ True  True  True]]

[[ True  True  True]
 [ True  True  True]]


In [288]:
# Imprimindo comparação
print(np.logical_and(arr % 2 == 0, arr % 4 == 0))
print()
print(np.logical_or(arr % 2 == 0, arr % 4 == 0))

[[ True False False False  True False False]
 [False  True False False False  True False]
 [False False  True False False False  True]]

[[ True False  True False  True False  True]
 [False  True False  True False  True False]
 [ True False  True False  True False  True]]


### (1.4.3) Operações Estatísticas

In [289]:
# Definindo array
array_data = np.arange(1, 11)

# Embalhando os dados
np.random.shuffle(array_data)

# Visualizar
array_data

array([ 8, 10,  5,  9,  7,  1,  3,  4,  2,  6])

In [137]:
# Calculando as Estatísticas de Ordem
print(f"Mínimo: {np.min(array_data)}")
print(f"Q1 (25%): {np.quantile(array_data, 0.25)}")
print(f"Q2 (50%): {np.quantile(array_data, 0.50)}")
print(f"Q3 (75%): {np.quantile(array_data, 0.75)}")
print(f"Máximo: {np.max(array_data)}")

Mínimo: 1
Q1 (25%): 3.25
Q2 (50%): 5.5
Q3 (75%): 7.75
Máximo: 10


In [138]:
# Calculando Medidas de Tendência Central
print("Média:", np.mean(array_data))
print("Mediana:", np.median(array_data))

Média: 5.5
Mediana: 5.5


In [139]:
# Calculando Medidas de Variabilidade
print("Desvio padrão:", np.std(array_data))
print("Variância:", np.var(array_data))
print(f"Amplitude Total: {np.max(array_data) - np.min(array_data)}")

Desvio padrão: 2.8722813232690143
Variância: 8.25
Amplitude Total: 9


In [140]:
# Outras medidas
print("Dados ordenados:", np.sort(array_data))
print(f"Tamanho da Amostra: {len(array_data)}")
print("Soma total:", np.sum(array_data))

Dados ordenados: [ 1  2  3  4  5  6  7  8  9 10]
Tamanho da Amostra: 10
Soma total: 55


In [290]:
# Defini-se estado aleatório (semente)
np.random.seed(123456789)

# Definido arrays
arr1 = np.random.randint(low=5, high=15, size=25)
arr2 = np.random.rand(25) * 100

# Visualizar
print(arr1)
print()
print(arr2)

[13  7 14 12  9  8  9  5  8  9  7  9 10  6  8 13 12 10 14  5 10  8  5  5
  8]

[40.66554425 98.02586037 54.20651799 24.22946119 25.22416821 56.51557864
 13.33368799 87.62585589 48.0331855  28.3325868  89.22107811 82.76319705
 97.99704702 86.72329719 19.3505653  45.44906731 80.51827816 74.72314167
 91.99597185 22.04699297 99.7953098  60.27965203  3.55184574 55.55210785
 31.96425219]


Considere `arr1` como tempo de serviço e `arr2` como salário. Qual o grau de dependência entre eles?

In [142]:
# Matriz de Covariâncias
np.cov(arr1, arr2)

array([[  7.87333333,   8.04334875],
       [  8.04334875, 926.87999914]])

In [143]:
# Matriz de Correlações
np.corrcoef(arr1, arr2)

array([[1.        , 0.09415553],
       [0.09415553, 1.        ]])

In [291]:
# Defini-se estado aleatório (semente)
np.random.seed(123456789)

# Definido arrays
arr1 = np.random.randint(low=5, high=15, size=25)
arr2 = 2.5 * arr1 + np.random.normal(loc=0, scale=10, size=25)

# Visualizar
print(arr1)
print()
print(arr2)

[13  7 14 12  9  8  9  5  8  9  7  9 10  6  8 13 12 10 14  5 10  8  5  5
  8]

[35.39492156 16.93733403 19.0904603  32.59690981 26.65963394  4.18277233
  4.33068236 10.85071787 17.96803779  8.81522433 23.68565475 30.13558025
 25.61256487  9.87536839 20.23564359 12.30633438 50.5862978  29.195676
 25.20784859 11.45271441 33.70079148 27.03946018 14.09027327 10.81570894
  4.13313471]


In [292]:
# Matriz de Covariâncias
np.cov(arr1, arr2)

array([[  7.87333333,  16.55343433],
       [ 16.55343433, 133.16929709]])

In [293]:
# Matriz de Correlações
np.corrcoef(arr1, arr2)

array([[1.        , 0.51121871],
       [0.51121871, 1.        ]])

Mas e se o `array` que eu estou lidando não for numérico?

In [147]:
# Defini-se estado aleatório (semente)
np.random.seed(123456789)

# Definindo array
arr = np.random.binomial(n=1, p=2/3, size=25)

# Visualizar
print(f"Amostra Aleatória de uma Bernoulli(2/3):\n{arr}")

# Modificando para uma melhor visualização
arr_modif = np.where(arr == 1, "coroa", "cara")

# Visualizar
print(f"\nAmostra Aleatória de uma Bernoulli(2/3) modificada:\n{arr_modif}")

Amostra Aleatória de uma Bernoulli(2/3):
[1 1 1 0 1 0 0 1 0 1 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0]

Amostra Aleatória de uma Bernoulli(2/3) modificada:
['coroa' 'coroa' 'coroa' 'cara' 'coroa' 'cara' 'cara' 'coroa' 'cara'
 'coroa' 'cara' 'cara' 'cara' 'coroa' 'coroa' 'coroa' 'coroa' 'coroa'
 'coroa' 'cara' 'coroa' 'cara' 'coroa' 'coroa' 'cara']


In [148]:
# Quais valores únicos?
np.unique(arr_modif)

array(['cara', 'coroa'], dtype='<U5')

In [149]:
# Frequência dessas valores?
np.bincount(arr)

array([10, 15], dtype=int64)

In [150]:
# Quais valores únicos e suas frequências?
np.unique(arr_modif, return_counts=True)

(array(['cara', 'coroa'], dtype='<U5'), array([10, 15], dtype=int64))